### ISSUE TITLE
时间问题

### ISSUE THREAD

**Issue by wusuoweima** [iMoonLab/MeshNet#10]
正在学习你们的论文 “MeshNet: Mesh Neural Network for 3D Shape Representation”，想先问两个非算法方面的问题：
1. 好奇这篇论文各个阶段用的时间：从产生想法，到数据预处理完毕所用的时间；分类实验用的时间；写论文用的时间
2. 你是在本科期间完成的这篇论文吗？

**Comment by wusuoweima** [comment]
@thss15fyt @yifanfeng97

**Comment by thss15fyt** [comment]
@wusuoweima 感谢您对我们工作的关注：
1.本篇论文的研究有一定跨度，前期调研和预处理数据与后期工作的间隔较大，实际工作量应有 2 个多月的时间；
2.是在一作为本科，二作为研究生期间完成的。
