### ISSUE TITLE
 visualize .npy  or .npz

### ISSUE THREAD

**Issue by wusuoweima** [iMoonLab/MeshNet#11]
How to visualize .npy or  .npz files in the form of mesh?

**Comment by wusuoweima** [comment]
@thss15fyt

**Comment by thss15fyt** [comment]
To achieve the feature visualization in the paper, we need to draw each face with different colors respectively. So we use the `matplotlib` in Python as the visualization tool, drawing each triangular faces one by one. But it can not handle the relations of faces based on the position of camera. So we are still looking for tools that meet both of the above requirements.
