### ISSUE TITLE
How do you obtain the classification results of ModelNet as 91.9?

### ISSUE THREAD

**Issue by liang3588** [iMoonLab/MeshNet#18]
Thank you for providing your code. While I only get the best model with Acc of 89.16% and mAP of 79.81%. I refered to the previous questions about the best result, and kownd that your best result was trained from a more complex training strategy. So could you please give a brief description of the training strategy you use? Maybe I can implement it myself.

Thank you very much!

**Comment by ss892714028** [comment]
Did you use the provided npz files? I can replicate the recall numbers with no problem.

**Comment by thss15fyt** [comment]
Please refer to the new update and we provide a more stable training script to reproduce or even ourperform the results in paper.
