### ISSUE TITLE
FRC

### ISSUE THREAD

**Issue by yhl48** [iMoonLab/MeshNet#22]
Hi, could you clarify the purpose of the structural descriptor? It looks like FRC would also model the volume of a 3D object given that the inputs to FRC are the corners, but at the same time you mentioned that it would capture the inner structure of an object, which would be 2D. Is it wrong to assume that that part of the model would capture the volumetric information?

**Comment by thss15fyt** [comment]
Hi, thanks for your interest.

The structural descriptor is designed to capture features of local geometry on mesh without considerring the absolute spatial position of faces. The FRC takes the relative coordinates `corners - center` as input, and models the structural information of each polygon face in 3D space.
