### ISSUE TITLE
Program to convert original ModelNet OFF files to NPY files 

### ISSUE THREAD

**Issue by russell0** [iMoonLab/MeshNet#7]
Hi -- just to make sure we have the right workflow for converting meshes in OFF format to the NPY/NPZ training format, can you share the program that did these conversions from the original ModelNet 40 model files?  

http://modelnet.cs.princeton.edu/ 

https://en.wikipedia.org/wiki/OFF_(file_format)

**Comment by russell0** [comment]
Do any of these programs support the NPY format conversion?
http://3dvision.princeton.edu/code.html

**Comment by thss15fyt** [comment]
Hi, thanks for your attention to our work.
We have uploaded the transformation code from off files to our required npz format. Details about how to use the code are added to the `Data Preparation` in README.md. Hope that helps.

**Comment by Lordores** [comment]
大佬好，关于preprocess.py里要用到的pymesh这个工具,在安装的时候有什么注意的地方或者坑？我这里也是Ubuntu 16.04，但是一直装不成功。
我在“Linking CXX shared library ../../../python/pymesh/lib/libPyMesh-IGL.so”这个地方一直报错

**Comment by thss15fyt** [comment]
> 大佬好，关于preprocess.py里要用到的pymesh这个工具,在安装的时候有什么注意的地方或者坑？我这里也是Ubuntu 16.04，但是一直装不成功。
> 我在“Linking CXX shared library ../../../python/pymesh/lib/libPyMesh-IGL.so”这个地方一直报错

你好，我在安装 PyMesh 时的确遇到了一些问题，不过目前该库已经提供了可以直接通过 `pip` 安装的 release 版本，可以参看相关 issue [fix build so works with pip install](https://github.com/PyMesh/PyMesh/pull/157)。

**Comment by jaydenwu17** [comment]
Hi there,

The updated preprocess.py seems to have a few issues. I am running into problems when I try to convert the original off file from the ModelNet40 database:
Traceback (most recent call last):
  File "./preprocess_chair_imagine.py", line 73, in <module>
    faces_contain_this_vertex[v1].add(f)
TypeError: unhashable type: 'numpy.ndarray'

I am using python 3.6 btw.

**Comment by jaydenwu17** [comment]
Here is the chair_0001.off file I tested with the preprocess.py.
[chair_0001.off.zip](https://github.com/iMoonLab/MeshNet/files/3489224/chair_0001.off.zip)

**Comment by thss15fyt** [comment]
> Hi there,
> 
> The updated preprocess.py seems to have a few issues. I am running into problems when I try to convert the original off file from the ModelNet40 database:
> Traceback (most recent call last):
> File "./preprocess_chair_imagine.py", line 73, in 
> faces_contain_this_vertex[v1].add(f)
> TypeError: unhashable type: 'numpy.ndarray'
> 
> I am using python 3.6 btw.

@jaydenwu17 Sorry for the late reply. I have fixed the bug in `preprocess.py` and you could test it now. (For some reason I can't test in the environment with PyMesh now.)
