### ISSUE TITLE
how to extract 1024 faces 

### ISSUE THREAD

**Issue by JsBlueCat** [iMoonLab/MeshNet#9]
can i use mlp to simplify mesh data?

**Comment by thss15fyt** [comment]
@JsBlueCat Sorry for the late reply. I did not try to simplify the mesh data with MLP. Could you describe your idea in detail?

**Comment by tangwenming** [comment]
Thank you very much for your open source code. Can your obj source files (1024 faces obj) be open for download?

**Comment by liang3588** [comment]
Thank you very much for your open source code. Can your open the obj source files (1024 faces obj)  for download?

**Comment by thss15fyt** [comment]
We have presented new results based on [Manifold40](https://cloud.tsinghua.edu.cn/f/2a292c598af94265a0b8/?dl=1) (500 faces obj). See the README.md for processed dataset.

**Comment by tangwenming** [comment]
您的来信已收到！
